[package]
name = "chess-mos"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dia"
path = "src/bin/dia.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.6"

[dev-dependencies]
clippy = "0.0.302"